# Generated by Django 3.0.3 on 2023-12-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('circuitId', models.IntegerField(primary_key=True, serialize=False)),
                ('circuitRef', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('alt', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('constructorId', models.IntegerField(primary_key=True, serialize=False)),
                ('constructorRef', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driverId', models.IntegerField(primary_key=True, serialize=False)),
                ('driverRef', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('forename', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('raceId', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=255)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_app.Circuit')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusId', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('resultId', models.IntegerField(primary_key=True, serialize=False)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_app.Constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_app.Driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_app.Race')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_app.Status')),
            ],
        ),
    ]
