# Generated by Django 3.0.3 on 2023-12-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_app', '0002_auto_20231226_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driverId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
